### ISSUE TITLE
支持其他种类的淘口令

### ISSUE THREAD

**Issue by PorridgePi** [Coolkkmeat/TaobaoCommandParse#2]
有些淘口令并没有使用 ￥ 或 $。
例如这个：`€akuVc4tENOl€` 用了 €
应该把正则改成 `(￥|\$|\€)([a-zA-Z0-9]*)(￥|\$|\€)` 就好了。

然后似乎在[淘宝国际官网](https://world.taobao.com)上用不了，不确定为何。[淘宝搜索](https://s.taobao.com)可以正常使用。

**Comment by Coolkkmeat** [comment]
淘口令在 #1 中已经支持了，目前等待合并。
淘宝国际官网的问题应该是搜索框的id与淘宝搜索的不同，此问题已经添加到待办中了。
感谢支持。

**Comment by PorridgePi** [comment]
好的，谢谢！id 好像是 "mq"，name 还是 "q"。我不是很懂这个，但还是希望有点用！

**Comment by Coolkkmeat** [comment]
是这样的，id是`mq`，你说的很对。
感谢帮助。

**Comment by Coolkkmeat** [comment]
刚刚发布了`v1.2.0`，已经实现这些功能了。

**Comment by pplokijuhyg** [comment]
国际版不能使用已被修复，请耐心等待开发者的合并，原因是因为搜索的input是使用js动态添加的，$()只是页面被加载完毕，而不是所有的js操作完毕。

**Comment by Coolkkmeat** [comment]
> 国际版不能使用已被修复，请耐心等待开发者的合并，原因是因为搜索的input是使用js动态添加的，$()只是页面被加载完毕，而不是所有的js操作完毕。

已经合并，感谢提交。
