### ISSUE TITLE
新的淘口令开始和结束符

### ISSUE THREAD

**Issue by pixiandouban** [Coolkkmeat/TaobaoCommandParse#5]
从微博上搜集到的几个淘口令

1、 🎵e2Nocj7Tx1g📲，
发现把前后的标志符提换成 ￥也能跳转，就是把生面的口令手动替换成 ￥e2Nocj7Tx1g￥，脚本可以解析。

2、（￥OZGjcQKQkLE 
替换成 ￥OZGjcQKQkLE￥ 可以解析。

3、7(￥hxWAcj3Yiqt￥)/:/
替换成 ￥hxWAcj3Yiqt￥ 可以解析。

4、8/F2iBcQ6xCZB//
可以直接跳转，不知道规则

5、 ₳ZZPs16y5WCa₳
₳替换成￥，无效。（这个是口令过期失效了吗？）

6、￥2jRycicbvxe$ ​​​
可以直接跳转（前后标志不统一，是已经支持了吗?）

7、0_0(s0jWcizeD02(/ 
可以直接跳转解析。

8、₰XIyHc77mBqN🎵
在淘大象网页可以解析（未登录淘宝）

9、顺便问一下，能否添加一个开关和提示，打开之后进行搜索，输入错误或者无效口令，提示错误命令。

### 新添加
10、a:/😺yhSSc90Hk1L₤
在淘大象中，可以替换成 `yhSSc90Hk1L（即 前后无任何标志）、yhSSc90Hk1L₤（yhSSc90Hk1L₤，前后只有一个标志的）、₤yhSSc90Hk1L₤、😂yhSSc90Hk1L😂（♏yhSSc90Hk1L🛏，测试了几个 emoji，似乎是任意的 emoji 表情符号都可）、ǐyhSSc90Hk1Lǐ（变种拉丁字母）、高yhSSc90Hk1L高（ィyhSSc90Hk1Lあ，中日韩文）`

`感觉是不是除了 0-9a-zA-Z 之外的其他字符都是 标志/无效口令？`

**Comment by Coolkkmeat** [comment]
> 感谢您的Issue，给出了很详细的建议，对此项目的优化升级非常有帮助。

1/8：正在优化适配这种字符。
2：最后面没有终止字符应该不太好判断，正在尽力适配。
3/4/7：多重符号正在做优化。
5：这个淘口令应该不正确。
6：已经支持前后标志不统一的情况。
9：没太理解你的意思。我想如果输进去检测到会有提示，这个也正在做优化。

**Comment by pixiandouban** [comment]
9 的想法是，是否在脚本上加个开关，处于 on 的时候进行淘口令解析， off 的时候就不解析（不用脚本一直在查询了）

如果消耗资源忽略不计那就算了。想想其实也可以在 Tampermonkey 上 enable/disable 脚本。

10、是刚刚看到的，不知道是不是可以用许多无效字符来作为标志符，或者说 见到无效字符就去掉。

4、开头4的“多重符号”也知道规则了，就是 可以替换成 F2iBcQ6xCZB 进行解析。猜想是 开头出现 0-9a-zA-Z 之外的字符都算无效口令部分。
 
> 4、8/F2iBcQ6xCZB//
可以直接跳转，不知道规则

**Comment by Coolkkmeat** [comment]
9：脚本在检测到输入时，会自动匹配符号列表里的符号，如果检测到才会进行查询。所以资源消耗很低。
10：按照如上原理，比如emoji没有考虑到就会导致无法识别。或许可以按你说的依靠a-zA-Z0-9且规定字符数量进行匹配，但是不知道会不会造成误识别，还需要进行测试。

**Comment by septs** [comment]
```ts
function getSymbolRegExp() {
  const table = [
    /\x24-\x2f/,
    /\x80-\xff/,
    /\u0e00-\u0e7f/,
    /\u1780-\u17ff/,
    /\u20a0-\u20cf/,
    /\u3000-\u303f/,
    /\ufb50-\ufdff/,
    /\u{1f300}-\u{1f64f}/,
  ];
  const symbols = table.map(({ source }) => source).join('');
  return new RegExp(`[${symbols}]([a-zA-Z0-9]{11})[${symbols}]`, 'u');
}

if (getSymbolRegExp().test('🎵e2Nocj7Tx1g📲')) {
    console.log(RegExp.$1) // returns "e2Nocj7Tx1g"
}
```

**Comment by septs** [comment]
@Coolkkmeat 可以试试我这一组正则方案

**Comment by Coolkkmeat** [comment]
> @Coolkkmeat 可以试试我这一组正则方案

收到！感谢提供建议，我会在后续进行查看。
