### ISSUE TITLE
是不是已经完全失效了 = =

### ISSUE THREAD

**Issue by 474364707** [Coolkkmeat/TaobaoCommandParse#6]

**Comment by Coolkkmeat** [comment]
您好，最新版已经修复~

**Comment by LuminescenceZzz** [comment]
请问下是只有edge有效吗，我用了火狐、Chrome都不行，只有edge可以，前者粘贴后好像会识别但是不跳转，后者没问题可以跳转。但是我已经用习惯了火狐了不太想用edge，这个问题有办法解决吗

**Comment by Coolkkmeat** [comment]
> 请问下是只有edge有效吗，我用了火狐、Chrome都不行，只有edge可以，前者粘贴后好像会识别但是不跳转，后者没问题可以跳转。但是我已经用习惯了火狐了不太想用edge，这个问题有办法解决吗

你好，我这边开发和测试均是在 Chrome 下完成的，等下我去看看 Edge 和 Firefox 的兼容性。

**Comment by LuminescenceZzz** [comment]
> 

好的，非常感谢

**Comment by Coolkkmeat** [comment]
> > 
> 
> 好的，非常感谢

已修复，我这边测试三种浏览器都可以支持，更新一下就可以使用了。

**Comment by LuminescenceZzz** [comment]
可以用了，非常感谢

**Comment by LuminescenceZzz** [comment]
好像又寄了，不会跳转

**Comment by Coolkkmeat** [comment]
> 好像又寄了，不会跳转

经测试，`taobaoke`访问异常，`taodaxiang`还可以正常访问。

**Comment by LuminescenceZzz** [comment]
可是我这边换成taodaxiang后还是不会跳转，试了几个浏览器，也重新安装过脚本了

**Comment by Coolkkmeat** [comment]
> 可是我这边换成taodaxiang后还是不会跳转，试了几个浏览器，也重新安装过脚本了

我这边一开始也是，换成`s.taobao.com`刷新几下又可以了，考虑可能是数据源那边做的限制，在没有稳定数据源的情况下目前没解决办法了。

**Comment by LuminescenceZzz** [comment]
好吧，感谢

**Comment by Coolkkmeat** [comment]
> 好吧，感谢

感谢反馈~
